---

# Provisions a single AWS instance and provides it back to the containing play
# context

- name: Provision Instance
  hosts: localhost
  gather_facts: False
  roles:
    - role: launch_isc_ec2
      instance_tags: '{"Name":"{{instance_name_tag}}"}'
      name_tag: "{{instance_name_tag}}"
