---
# prepare an instance for edx installation (see
# https://github.com/edx/configuration/wiki/edX-Ubuntu-12.04-64-bit-Installation)

- name: Prepare instance for edx installation
  hosts: launched
  sudo: yes
  user: ubuntu
  gather_facts: True
  roles:
    - role: prep_isc_ec2

  post_tasks:
    - name: Wrap up
      debug: msg={{item}}
      with_items:
        - Your server is now ready to build edx.
        - Please ssh to {{inventory_hostname}} and run the following commands
        - $ cd {{prep_isc_ec2_bootstrap_dir}}/playbooks
        - $ sudo ansible-playbook -c local ./isc_edx_sandbox.yml -i "localhost," -e "edx_ansible_source_repo={{edx_ansible_source_repo}} configuration_version={{configuration_version}} edx_platform_repo={{edx_platform_repo}} edx_platform_version={{edx_platform_version}}"
