---
# prepares a fresh ec2 ubuntu 12.04 instance for EdX installation

- name: Update apt-get package list
  apt: update_cache=yes, cache_valid_time=86400
  ignore_errors: yes

- name: Upgrade apt-get
  apt: upgrade=yes

- name: Install basic system packages
  apt: name={{','.join(prep_isc_ec2_packages)}} state=present update_cache=yes

- name: Install and upgrade pip and virtualenv
  pip: name={{item}} extra_args=--upgrade
  with_items:
    - pip
    - virtualenv

- name: Clone configuration repository
  git: repo={{edx_ansible_source_repo}} version={{configuration_version}} dest={{prep_isc_ec2_bootstrap_dir}}

- name: Install configuration requirements
  pip: requirements={{prep_isc_ec2_bootstrap_dir}}/requirements.txt
