---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    COMMON_ENABLE_BASIC_AUTH: True
    COMMON_HTPASSWD_USER: isc
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    edxapp_use_custom_theme: true  # false to disable & use std. theme
    edxapp_theme_name: "isc"
    edxapp_theme_source_repo: "https://github.com/appsembler/edx-theme.git"
    edxapp_theme_version: "isc"
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
  roles:
    - role: isc_nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - role: 'edxapp'
      custom_requirements_file: /var/tmp/customizations/requirements/custom_requirements.txt
    - role: isc_apply_customizations
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - ora
    - certs
    - isc_edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
